version: 2

project_name: hawser

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/hawser
    binary: hawser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    flags:
      - -trimpath

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - scripts/install.sh
      - scripts/hawser.service

dockers:
  - image_templates:
      - "ghcr.io/finsys/hawser:{{ .Version }}-amd64"
      - "ghcr.io/finsys/hawser:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: amd64
    dockerfile: Dockerfile

  - image_templates:
      - "ghcr.io/finsys/hawser:{{ .Version }}-arm64"
      - "ghcr.io/finsys/hawser:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: arm64
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/finsys/hawser:{{ .Version }}"
    image_templates:
      - "ghcr.io/finsys/hawser:{{ .Version }}-amd64"
      - "ghcr.io/finsys/hawser:{{ .Version }}-arm64"

  - name_template: "ghcr.io/finsys/hawser:latest"
    image_templates:
      - "ghcr.io/finsys/hawser:latest-amd64"
      - "ghcr.io/finsys/hawser:latest-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Finsys
    name: hawser
  prerelease: auto
  draft: false
  name_template: "v{{ .Version }}"
